apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- argocd-namespace.yaml        
- argo-operatorGroup.yaml
- argocd-operator-subscription.yaml 
- service_account.yaml
- role.yaml 
- role_binding.yaml
- argocd-instance.yaml
- argo-console-link.yaml
namespace: argo
